- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/mysql/init.sql
- packages/apollo-collaboration-server/src/main.ts
This adds a Docker-based development environment that can easily be integrated with Visual Studio Code. More information about developing in a container can be found [here](https://code.visualstudio.com/docs/remote/containers), but the basic steps are to install Docker on your computer and the [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension in vscode and then run the command "Reopen in Container" in vscode. (If on Linux, you'll have to install `docker-compose` separately, but on Windows and Mac it comes packaged with Docker Desktop).
It actually uses two Docker containers together with `docker-compose`, a Node.js container with `npm`, `yarn`, etc. installed, and a MySQL container for the database. This helps keeps …
> Add Docker-based dev environment

- packages/apollo-schemas/src/feature.schema.ts
This adds compound indexes on refSeq+start and refSeq+end to the feature collection. This makes it so that this query that we do will use the index and work faster:
https://github.com/GMOD/jbrowse-plugin-apollo/blob/ccfb44117b04438269b245b85c752cfff8570200/packages/apollo-collaboration-server/src/features/features.service.ts#L228-L234
> Add Feature schema indexes

- packages/apollo-collaboration-server/src/assemblies/assemblies.module.ts
- packages/apollo-collaboration-server/src/features/features.module.ts
- packages/apollo-collaboration-server/src/refSeqs/refSeqs.module.ts
According to the [NestJS docs](https://docs.nestjs.com/techniques/mongodb#model-injection):
> If you also want to use the models in another module, add MongooseModule to the exports section of CatsModule and import CatsModule in the other module.
This applies that pattern, exporting `MongooseModule` from `AssembliesModule` and `RefSeqsModule` and importing those modules into `FeaturesModule`.
> Don't register schema multiple times

- .yarn/sdks/eslint/lib/api.js
- .yarn/sdks/eslint/package.json
- .yarn/sdks/typescript/lib/tsserver.js
- .yarn/sdks/typescript/lib/tsserverlibrary.js
VS Code 1.66 changed how it handles file, which broke the ZipFS extension we use to view the compressed yarn cache (equivalent to old node_modules). This updates yarn's SDK files to fix it.
> Update yarn libs to fix ZipFS bug

- packages/apollo-collaboration-server/src/change/change.service.ts
- packages/apollo-shared/src/ChangeManager/ChangeManager.ts
- packages/apollo-shared/src/Validations/CoreValidation.ts
- packages/apollo-shared/src/Validations/index.ts
- packages/jbrowse-plugin-apollo/src/ApolloView/stateModel.ts
This adds a core validation (that doesn't do anything yet) and adds evaluation of the validation to the server (validations were already evaluated on the client). Draft for now since it will be merged after #78, and will probably need to be updated after that is merged to move the validation to the service instead of the controller.
> Add and run core validation

- packages/apollo-collaboration-server/src/changes/changes.service.ts
- packages/apollo-shared/package.json
- packages/apollo-shared/src/ChangeManager/Change.ts
- packages/apollo-shared/src/ChangeManager/FeatureChange.ts
- packages/apollo-shared/src/ChangeManager/LocationEndChange.ts
- packages/apollo-shared/src/ChangeManager/LocationStartChange.ts
- yarn.lock
This adds the ability to pass the NestJS logger into the change objects. That means in a change you can use `this.logger.verbose('message')` and it will use NestJS's logger, which can be set to various log levels. It will use e.g. `console.verbose` when running in the browser.
> Add option to pass NestJS logger to change objects

- packages/apollo-collaboration-server/.development.env
- packages/apollo-collaboration-server/src/assemblies/dto/create-assembly.dto.ts
- packages/apollo-collaboration-server/src/changes/changes.service.ts
- packages/apollo-collaboration-server/src/features/features.controller.ts
- packages/apollo-collaboration-server/src/features/features.service.ts
- packages/apollo-collaboration-server/src/main.ts
- packages/apollo-collaboration-server/src/refSeqs/dto/find-refSeq.dto.ts
- packages/apollo-collaboration-server/src/refSeqs/refSeqs.controller.ts
- packages/apollo-collaboration-server/src/refSeqs/refSeqs.service.ts
- packages/apollo-collaboration-server/test/data/assemblies.json
- packages/apollo-collaboration-server/test/data/features.json
- packages/apollo-schemas/src/assembly.schema.ts
- packages/apollo-shared/src/BackendDrivers/CollaborationServerDriver.ts
- packages/jbrowse-plugin-apollo/package.json
- packages/jbrowse-plugin-apollo/src/ApolloRenderer/components/ApolloRendering.tsx
- packages/jbrowse-plugin-apollo/src/ApolloView/components/ApolloView.tsx
- packages/jbrowse-plugin-apollo/src/ApolloView/components/CollaborationSetup.tsx
- packages/jbrowse-plugin-apollo/src/ApolloView/stateModel.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel.ts
- packages/jbrowse-plugin-apollo/tsconfig.json
- yarn.lock
Closes #64
Closes #68 
This moves everything over so that the server-side GFF3 is no longer used, everything happens in MongoDB. It also updates the testing feature data a bit, to better match what the `uploadGFF3` endpoint produces.
> Use endpoints in UI that use MongoDB, remove server-side GFF3

- packages/apollo-collaboration-server/src/changes/changes.service.ts
- packages/apollo-collaboration-server/src/changes/dto/create-change.dto.ts
- packages/apollo-shared/package.json
- packages/apollo-shared/src/ChangeManager/Change.ts
- packages/apollo-shared/src/ChangeManager/LocationEndChange.ts
- packages/apollo-shared/src/ChangeManager/LocationStartChange.ts
- packages/apollo-shared/src/ChangeManager/TypeChange.ts
- packages/jbrowse-plugin-apollo/src/ApolloDetailsView/components/ApolloDetailsView.tsx
- packages/jbrowse-plugin-apollo/src/ApolloRenderer/components/ApolloRendering.tsx
- yarn.lock
This PR allows either of these changes to be valid:
```json
{
"typeName": "LocationEndChange",
"changedIds": [
"1ccdfd84-587f-49aa-be63-8dab88a61b1b"
],
"assemblyId": "624a7e97d45d7745c2532b01",
"featureId": "1ccdfd84-587f-49aa-be63-8dab88a61b1b",
"oldEnd": 2200,
"newEnd": 2300
}
```
```json
{
"typeName": "LocationEndChange",
"changedIds": [
"1ccdfd84-587f-49aa-be63-8dab88a61b1b"
],
"assemblyId": "624a7e97d45d7745c2532b01",
"changes": [
{
"featureId": "1ccdfd84-587f-49aa-be63-8dab88a61b1b",
"oldEnd": 2200,
"newEnd": 2300
}
]
}
```
Previously only the second one was valid.
> Don't enforce multiple sub-changes in a change

- packages/apollo-shared/src/BackendDrivers/AnnotationFeature.ts
- packages/apollo-shared/src/BackendDrivers/BackendDriver.ts
- packages/apollo-shared/src/BackendDrivers/CollaborationServerDriver.ts
- packages/apollo-shared/src/ChangeManager/LocationEndChange.ts
- packages/apollo-shared/src/ChangeManager/LocationStartChange.ts
- packages/apollo-shared/src/ChangeManager/TypeChange.ts
- packages/jbrowse-plugin-apollo/src/ApolloDetailsView/components/ApolloDetailsView.tsx
- packages/jbrowse-plugin-apollo/src/ApolloDetailsView/stateModel.ts
- packages/jbrowse-plugin-apollo/src/ApolloRenderer/components/ApolloRendering.tsx
- packages/jbrowse-plugin-apollo/src/ApolloView/stateModel.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel.ts
This adds basic subfeature glyphs that work for any generic number and depth of subfeatures. Each feature and child features can have their boundaries dragged. Specialized glyphs (e.g. gene feature glyphs) to come later.
> Add glyphs for subfeatures

- packages/apollo-collaboration-server/src/changes/changes.service.ts
- packages/apollo-collaboration-server/src/files/files.controller.ts
- packages/apollo-collaboration-server/src/files/files.module.ts
- packages/apollo-collaboration-server/src/files/files.service.ts
- packages/apollo-shared/src/ChangeManager/AddAssemblyAndFeaturesFromFileChange.ts
- packages/apollo-shared/src/ChangeManager/AddAssemblyFromFileChange.ts
- packages/apollo-shared/src/ChangeManager/AddFeaturesFromFileChange.ts
- packages/apollo-shared/src/ChangeManager/Change.ts
- packages/apollo-shared/src/ChangeManager/FeatureChange.ts
- packages/jbrowse-plugin-apollo/package.json
- packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/configSchema.ts
- packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/model.ts
- packages/jbrowse-plugin-apollo/src/components/AddAssembly.tsx
- packages/jbrowse-plugin-apollo/src/index.ts
- yarn.lock
This PR reduces the plugin bundle size. As a reference, the development UMD build before this was 27966 lines (24.5s to build) and after this is 10730 lines (19.4s to build). Main changes were:
- Use more standard imports from `@jbrowse/core` so as to not accidentally bundle JBrowse core code
- Do node operations (e.g. unzipping, creating streams) in the server and pass the handles for those methods into the shared changes
- Use our own ObjectId generator and remove `bson` package, since it wasn't being tree-shaken.
> Reduce plugin bundle size

- packages/apollo-collaboration-server/package.json
- packages/apollo-collaboration-server/src/features/features.service.ts
- packages/apollo-collaboration-server/test/data/features.json
- packages/apollo-mst/README.md
- packages/apollo-mst/package.json
- packages/apollo-mst/src/AnnotationFeature.ts
- packages/apollo-mst/src/index.ts
- packages/apollo-mst/tsconfig.json
- packages/apollo-schemas/package.json
- packages/apollo-schemas/src/feature.schema.ts
- packages/apollo-shared/package.json
- packages/apollo-shared/src/BackendDrivers/BackendDriver.ts
- packages/apollo-shared/src/BackendDrivers/CollaborationServerDriver.ts
- packages/apollo-shared/src/BackendDrivers/index.ts
- packages/apollo-shared/src/ChangeManager/Change.ts
- packages/apollo-shared/src/ChangeManager/CopyFeatureChange.ts
- packages/apollo-shared/src/ChangeManager/FeatureChange.ts
- packages/apollo-shared/src/ChangeManager/LocationEndChange.ts
- packages/apollo-shared/src/ChangeManager/LocationStartChange.ts
- packages/apollo-shared/src/ChangeManager/TypeChange.ts
- packages/apollo-shared/src/Validations/ParentChildValidation.ts
- packages/jbrowse-plugin-apollo/package.json
- packages/jbrowse-plugin-apollo/src/ApolloDetailsView/components/ApolloDetailsView.tsx
- packages/jbrowse-plugin-apollo/src/ApolloDetailsView/stateModel.ts
- packages/jbrowse-plugin-apollo/src/ApolloRenderer/components/ApolloRendering.tsx
- packages/jbrowse-plugin-apollo/src/ApolloView/stateModel.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel.ts
- yarn.lock
This splits some mobx-state-tree code from the `apollo-shared` package to a new `apollo-mst` package. It then makes the features in mobx-state-tree and the Mongoose schemas have the same structure so that a snapshot from MST can be loaded in to MongoDB.
> Standardize feature structure on front and back ends

- .github/workflows/pull_request.yml
- package.json
- packages/apollo-mst/package.json
- packages/apollo-shared/package.json
- packages/jbrowse-plugin-apollo/jest.config.js
- packages/jbrowse-plugin-apollo/jestSetup.js
- packages/jbrowse-plugin-apollo/package.json
- packages/jbrowse-plugin-apollo/src/ApolloSequenceAdapter/ApolloSequenceAdapter.test.ts
- packages/jbrowse-plugin-apollo/src/ApolloSequenceAdapter/ApolloSequenceAdapter.ts
- packages/jbrowse-plugin-apollo/src/ApolloSequenceAdapter/configSchema.ts
- packages/jbrowse-plugin-apollo/src/ApolloSequenceAdapter/index.ts
- packages/jbrowse-plugin-apollo/src/index.ts
- packages/jbrowse-plugin-apollo/src/session.ts
- packages/jbrowse-plugin-apollo/tsconfig.json
- yarn.lock
Resolves #44 
With this, the sequence track shows the sequence for an Apollo assembly, and the "Get sequence" from the rubber band menu works.
Draft until https://github.com/GMOD/jbrowse-components/pull/3183 is merged.
Also includes some updates to the plugin test config, a test for the adapter, and a new CI step that runs the tests on PRs.
> Add sequence adapter for viewing and retrieving sequences

- packages/apollo-shared/src/BackendDrivers/BackendDriver.ts
- packages/apollo-shared/src/BackendDrivers/CollaborationServerDriver.ts
- packages/apollo-shared/src/ChangeManager/AddAssemblyAndFeaturesFromFileChange.ts
- packages/apollo-shared/src/ChangeManager/AddAssemblyFromFileChange.ts
- packages/apollo-shared/src/ChangeManager/AddFeaturesFromFileChange.ts
- packages/apollo-shared/src/ChangeManager/Change.ts
- packages/apollo-shared/src/ChangeManager/ChangeManager.ts
- packages/apollo-shared/src/ChangeManager/CopyFeatureChange.ts
- packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/model.ts
- packages/jbrowse-plugin-apollo/src/ApolloRenderer/components/ApolloRendering.tsx
- packages/jbrowse-plugin-apollo/src/components/AddAssembly.tsx
- packages/jbrowse-plugin-apollo/src/components/CopyFeature.tsx
- packages/jbrowse-plugin-apollo/src/components/ImportFeatures.tsx
- packages/jbrowse-plugin-apollo/src/index.ts
- packages/jbrowse-plugin-apollo/src/session.ts
This uses `changeManager.submitChange` instead of calling the `/change` API endpoint directly, so it goes through all the verifications and has better type checking on the change object. It also adds a way to select a particular collaboration server if multiple are configured when adding an assembly.
> Use submitChange instead of calling change endpoint

- packages/apollo-mst/src/AnnotationFeature.ts
- packages/jbrowse-plugin-apollo/src/ApolloRenderer/components/ApolloRendering.tsx
As noticed in the meeting today, the display was not correct when the region was reversed. This adds that support.
> Add support for viewing LinearApolloDisplay in reversed LGV

- packages/apollo-collaboration-server/src/changes/changes.service.ts
- packages/apollo-collaboration-server/src/main.ts
- packages/apollo-shared/src/ChangeManager/ChangeManager.ts
- packages/apollo-shared/src/Validations/ValidationSet.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/ApolloDetails.tsx
- packages/jbrowse-plugin-apollo/src/index.ts
- packages/jbrowse-plugin-apollo/src/session.ts
This creates a `validationRegistry` that's analogous to the `changeRegistry`, a global singleton where all validations are registered. The validations get registered in the initial app bootstrap. This PR also moves the registration of the changes to that same bootstrap step as well.
This addresses part of #136
> Validation registry

- packages/jbrowse-plugin-apollo/src/ApolloRenderer/components/ApolloRendering.tsx
- packages/jbrowse-plugin-apollo/src/session.ts
Apologies I didn't open this last night.
Current implementation: update collaborator location on mouse move; overlay rectangle over feature that collaborator is currently moused over.
Current limitations:
- overlay locked to top of track (for testing)
- overlay locked to green (should be different colour for each collaborator)
- constantly updating/rendering whenever moused over feature probably inefficient
- doesn't seem to be working for anything but the top feature on the track and disappears instantly - can't work out why.
> Indicator of Collaborator location

- packages/apollo-collaboration-server/src/app.module.ts
- packages/apollo-collaboration-server/src/assemblies/assemblies.module.ts
- packages/apollo-collaboration-server/src/assemblies/assemblies.service.ts
- packages/apollo-collaboration-server/src/changes/changes.service.ts
- packages/apollo-collaboration-server/src/features/features.module.ts
- packages/apollo-collaboration-server/src/files/files.module.ts
- packages/apollo-collaboration-server/src/main.ts
- packages/apollo-collaboration-server/src/operations/operations.module.ts
- packages/apollo-collaboration-server/src/operations/operations.service.spec.ts
- packages/apollo-collaboration-server/src/operations/operations.service.ts
- packages/apollo-shared/src/Changes/AddAssemblyAndFeaturesFromFileChange.ts
- packages/apollo-shared/src/Changes/AddAssemblyFromFileChange.ts
- packages/apollo-shared/src/Changes/AddFeatureChange.ts
- packages/apollo-shared/src/Changes/AddFeaturesFromFileChange.ts
- packages/apollo-shared/src/Changes/CopyFeatureChange.ts
- packages/apollo-shared/src/Changes/DeleteAssemblyChange.ts
- packages/apollo-shared/src/Changes/DeleteFeatureChange.ts
- packages/apollo-shared/src/Changes/DeleteUserChange.ts
- packages/apollo-shared/src/Changes/FeatureAttributeChange.ts
- packages/apollo-shared/src/Changes/LocationEndChange.ts
- packages/apollo-shared/src/Changes/LocationStartChange.ts
- packages/apollo-shared/src/Changes/TypeChange.ts
- packages/apollo-shared/src/Changes/UserChange.ts
- packages/apollo-shared/src/Changes/abstract/Change.ts
- packages/apollo-shared/src/Operations/GetAssembliesOperation.ts
- packages/apollo-shared/src/Operations/abstract/Operation.ts
- packages/apollo-shared/src/Operations/abstract/index.ts
- packages/apollo-shared/src/Operations/index.ts
- packages/apollo-shared/src/index.ts
- packages/jbrowse-plugin-apollo/src/ChangeManager.ts
Adds a base abstract class Operation that is now the base of the Change abstract class. Adds GetAssembliesOperation as the first class to use the new base class.
Fixes #165
> Add Operations and GetAssembliesOperation

- docker-compose.yml
- docker/.development.env
- docker/session-secret
- docs/apollo.env
- docs/deployment.md
- packages/apollo-collaboration-server/.development.env
- packages/apollo-collaboration-server/package.json
- packages/apollo-collaboration-server/src/app.module.ts
- packages/apollo-collaboration-server/src/declare.d.ts
- packages/apollo-collaboration-server/src/main.ts
- yarn.lock
By default, `express-session` uses an in-memory session store. When we run a production build, it warns that the default in-memory store is not meant for production and won't scale past a single process. This PR switches to a MongoDB-backed session store, [`connect-mongodb-session`](https://github.com/mongodb-js/connect-mongodb-session).
> Use connect-mongodb-session for express session

- packages/apollo-common/src/Change.ts
- packages/apollo-mst/src/AnnotationFeature.ts
- packages/apollo-mst/src/index.ts
- packages/apollo-shared/src/Changes/DeleteFeatureChange.ts
- packages/jbrowse-plugin-apollo/src/ApolloSixFrameRenderer/ApolloSixFrameRenderer.tsx
- packages/jbrowse-plugin-apollo/src/ApolloSixFrameRenderer/components/ApolloRendering.tsx
- packages/jbrowse-plugin-apollo/src/ApolloSixFrameRenderer/configSchema.ts
- packages/jbrowse-plugin-apollo/src/ApolloSixFrameRenderer/index.ts
- packages/jbrowse-plugin-apollo/src/BackendDrivers/BackendDriver.ts
- packages/jbrowse-plugin-apollo/src/BackendDrivers/CollaborationServerDriver.ts
- packages/jbrowse-plugin-apollo/src/SixFrameFeatureDisplay/components/TrackLines.tsx
- packages/jbrowse-plugin-apollo/src/SixFrameFeatureDisplay/components/index.ts
- packages/jbrowse-plugin-apollo/src/SixFrameFeatureDisplay/configSchema.ts
- packages/jbrowse-plugin-apollo/src/SixFrameFeatureDisplay/index.ts
- packages/jbrowse-plugin-apollo/src/SixFrameFeatureDisplay/stateModel.ts
- packages/jbrowse-plugin-apollo/src/index.ts
- packages/jbrowse-plugin-apollo/src/makeDisplayComponent.tsx
- packages/jbrowse-plugin-apollo/src/session.ts
Very basic implementation.
I have used the LinearApolloDisplay as a basis for a new display: SixFrameFeatureDisplay (name expected to change). Most of the logic change is in the featureLayout method in stateModel.ts. Where before, new rows were added whenever features would potentially overlap, I am now tying the row number directly to the phase of each given feature. Naturally, as most features don't have a phase in the gff file, we end up with virtually all features plotted being CDS (but this is expected behaviour in Artemis), and I have to dig down two "generations" to find these CDS features for a given "gene" feature.
Still to do:
1) connecting lines between each CDS feature belonging to a common parent.
2) The central tracks representing forward/reverse strands (or at least a …
> Add six frame feature display

- packages/jbrowse-plugin-apollo/package.json
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/ApolloDetails.tsx
- packages/jbrowse-plugin-apollo/src/components/ManageUsers.tsx
- packages/jbrowse-plugin-apollo/src/components/ViewChangeLog.tsx
- yarn.lock
JBrowse main branch has moved to `@mui/x-data-grid` v6. This PR adds the needed changes in `jbrowse-plugin-apollo` for that update.
> Update mui/x-data-grid to v6

- packages/apollo-shared/package.json
- yarn.lock
Was not remembering to create an ID for the parent feature if it didn't
have one, but only when executing on the client.
This led to the behavior in #204 because:
> 2. In my case, I added a new sub-feature which type was **_exon_region_** to existing **_exon_** which start is 69796 and end is 73033.
`AddFeatureChange.executeOnServer` creates an ID for the parent feature (which didn't already have one), but **only on the server**. Parent still has no ID in the client data store.
> 3. I exported the assembly (GFF3), OK.
Parent still has no ID in the client data store, but that's OK.
> 4. I opened the exon's "_**Modify feature attribute**_" -modal window from context menu. Without making any modification, I pressed "_**Submit changes**_"
Attributes in the client data store, with no ID, are …
> fix #204 in AddFeatureChange.executeOnClient

- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/BoxGlyph.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/CanonicalGeneGlyph.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/GenericChildGlyph.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/ImplicitExonGeneGlyph.ts
This adds a change to the rendering so that if a feature is selected, it renders differently. Works in dark and light modes.
> Show selected feature with rendering

- packages/jbrowse-plugin-apollo/src/components/DeleteAssembly.tsx
In *Delete Assembly* menu display the first assembly availaible instead of showing a blank box.
> Set default assembly in *Delete Assembly* menu

- packages/jbrowse-plugin-apollo/src/session/ClientDataStore.ts
While working just now I discovered that the assemblies and feature data are being preserved in the session snapshots.
This isn't what we want for obvious reasons.
> don't reload feature data from session snapshot

- packages/apollo-collaboration-server/src/features/features.controller.ts
- packages/apollo-collaboration-server/src/features/features.service.ts
- packages/apollo-schemas/src/feature.schema.ts
- packages/jbrowse-plugin-apollo/src/ApolloTextSearchAdapter/ApolloTextSearchAdapter.ts
- packages/jbrowse-plugin-apollo/src/ApolloTextSearchAdapter/configSchema.ts
- packages/jbrowse-plugin-apollo/src/ApolloTextSearchAdapter/index.ts
- packages/jbrowse-plugin-apollo/src/components/ImportFeatures.tsx
- packages/jbrowse-plugin-apollo/src/index.ts
- packages/jbrowse-plugin-apollo/src/session/session.ts
Searches the mongodb *features* collection for matches to a query. A couple of notes:
* This searches all (and only) the documents in the *features* collection. This means that if the loaded assembly(s) do not contain the query but another assembly contains it, you still get hits from the search.
* If a query returns multiple features, the order of the hits in the selection box is in seemingly random order. E.g.:
> Implement search-by-feature

- packages/jbrowse-plugin-apollo/src/ApolloTextSearchAdapter/ApolloTextSearchAdapter.ts
- packages/jbrowse-plugin-apollo/src/BackendDrivers/BackendDriver.ts
- packages/jbrowse-plugin-apollo/src/BackendDrivers/CollaborationServerDriver.ts
- packages/jbrowse-plugin-apollo/src/BackendDrivers/InMemoryFileDriver.ts
This PR includes edits suggested by Garrett at yesterday's meeting.
> Make feature searching use backend driver

- .github/workflows/pull_request.yml
- codecov.yml
- package.json
- packages/jbrowse-plugin-apollo/jest.config.js
- packages/jbrowse-plugin-apollo/package.json
Adds a Codecov report to PRs. Informational only for now, so it won't fail the PR's checks.
> Add coverage information to PRs

- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/LinearApolloDisplay.tsx
- packages/jbrowse-plugin-apollo/src/TabularEditor/model.ts
Use `Promise.resolve()` before setting ref in MST model to prevent infinite rendering loop. See `https://github.com/mobxjs/mobx/issues/3728#issuecomment-1715400931`.
> Fix display not rendering under React 18

- .yarnrc.yml
- packages/apollo-collaboration-server/package.json
- packages/apollo-collaboration-server/src/changes/changes.service.ts
- packages/apollo-collaboration-server/src/features/features.controller.ts
- packages/apollo-common/package.json
- packages/apollo-shared/package.json
- packages/jbrowse-plugin-apollo/package.json
- packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/model.ts
- yarn.lock
This updates a lot of the transitive dependencies (dependencies of our direct dependencies), and fixes a couple versions that needed to be fixed in some package.json files. It also changes the formatting of a few lines because the formatter dependencies got upgraded. The bulk of the changes are in yarn.lock, though.
> Upgrade transitive dependencies

- packages/apollo-collaboration-server/.development.env
- packages/apollo-collaboration-server/src/features/features.controller.ts
- packages/apollo-collaboration-server/src/features/features.module.ts
- packages/apollo-collaboration-server/src/features/features.service.ts
- packages/jbrowse-plugin-apollo/cypress/e2e/downloadGff.cy.ts
FASTA is now included in exported GFF3. Please, merge this only after [Bug_251_Download_not_working](https://github.com/GMOD/Apollo3/tree/Bug_251_Download_not_working) has been merged.
> Add sequence to exported GFF3

- packages/apollo-shared/src/Changes/DiscontinuousLocationEndChange.ts
- packages/apollo-shared/src/Changes/DiscontinuousLocationStartChange.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/Glyph.ts
- When we change CDS coordinate, the change is applied to the client but not to the server. It looks like we can't directly mark the attribute name as modified in mongoose due to which save isn't working as expected.
- Small fix in the tooltip to display discontinuous location coordinates correctly.
> Fix CDS with discontinuous locations coordinate change not saving to DB

- .eslintignore
- packages/apollo-common/src/AssemblySpecificChange.ts
- packages/jbrowse-plugin-apollo/src/ApolloTextSearchAdapter/ApolloTextSearchAdapter.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/Glyph.ts
- packages/jbrowse-plugin-apollo/src/TabularEditor/HybridGrid/Feature.tsx
- packages/jbrowse-plugin-apollo/src/TabularEditor/HybridGrid/HybridGrid.tsx
- packages/jbrowse-plugin-apollo/src/components/AddChildFeature.tsx
- packages/jbrowse-plugin-apollo/src/components/AddFeature.tsx
- packages/jbrowse-plugin-apollo/src/components/OpenLocalFile.tsx
Here's a handy cheat sheet for dealing with one-based vs zero-based files: https://www.biostars.org/p/84686/
Internally JBrowse uses zero-based coordinates, but GFF3 uses one-based coordinates, and since we didn't do any conversion, we ended up with this mismatch that @dariober noted in this image:
My first thought is that we should make the change in this PR so that the database is also zero-based, but if someone has a reason to keep the database the same and convert elsewhere, I'm certainly willing to listen.
@kyostiebi, does this change affect your CDS check calculations? Are there any other places this might have an effect you can think of?
Fixes #267
> Convert to zero-based coordinates on import

- docker/config/config.json
- docs/deployment.md
- packages/apollo-collaboration-server/src/authentication/authentication.controller.ts
- packages/apollo-collaboration-server/src/authentication/authentication.service.ts
- packages/apollo-collaboration-server/src/utils/google.guard.ts
- packages/apollo-collaboration-server/src/utils/microsoft.guard.ts
- packages/apollo-collaboration-server/src/utils/strategies/google.strategy.ts
- packages/apollo-collaboration-server/src/utils/strategies/microsoft.strategy.ts
- packages/jbrowse-plugin-apollo/cypress/fixtures/apollo_view.json
- packages/jbrowse-plugin-apollo/jbrowse_config.json
- packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/addMenuItems.ts
- packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/components/AuthTypeSelector.tsx
- packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/configSchema.ts
- packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/model.ts
- packages/jbrowse-plugin-apollo/src/ApolloSixFrameRenderer/components/ApolloRendering.tsx
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/Glyph.ts
- packages/jbrowse-plugin-apollo/src/TabularEditor/HybridGrid/featureContextMenuItems.ts
- packages/jbrowse-plugin-apollo/src/components/ManageUsers.tsx
- packages/jbrowse-plugin-apollo/src/components/ModifyFeatureAttribute.tsx
- packages/jbrowse-plugin-apollo/src/index.ts
Previously each login method had a different endpoint on the backend and a different internet account type on the frontend. This simplifies things by using only one internet account type and one login endpoint.
> Simplify login to only a single endpoint

- .lintstagedrc.yml
- .prettierrc.lint-staged.mjs
- packages/apollo-cli/test/test.py
- packages/apollo-cli/test_data/tiny.fasta.gff3
- packages/apollo-collaboration-server/src/authentication/authentication.service.ts
- packages/apollo-shared/src/Checks/CDSCheck.ts
- packages/apollo-shared/src/GFF3/gff3ToAnnotationFeature.ts
When combining multiple CDS into a single internal feature, we want to keep both IDs. This wasn't happening, so this PR fixes that.
> Fix converted GFF3 properties

- packages/apollo-cli/README.md
- packages/apollo-cli/package.json
- packages/apollo-cli/src/commands/jbrowse/get-config.ts
- packages/apollo-cli/src/commands/jbrowse/set-config.ts
- packages/website/docs/cli/jbrowse.md
Fixes https://github.com/GMOD/Apollo3/issues/433, fixed #214 
Example:
```
apollo-cli % yarn dev jbrowse get-config --profile apollo > config.json
apollo-cli % jbrowse add-track https://ftp.ebi.ac.uk/pub/databases/havana/ngs_havana/CLS/updated_master_table/human/pacBioSII-Cshl-CapTrap_HpreCap_0+_Brain03Rep1.bam --indexFile https://ftp.ebi.ac.uk/pub/databases/havana/ngs_havana/CLS/updated_master_table/human/pacBioSII-Cshl-CapTrap_HpreCap_0+_Brain03Rep1.bam.bai --assemblyNames=66bb60e83db15a4a2aff224d
Added track with name "pacBioSII-Cshl-CapTrap_HpreCap_0+_Brain03Rep1" and trackId "pacBioSII-Cshl-CapTrap_HpreCap_0+_Brain03Rep1" to ./config.json
apollo-cli % yarn dev jbrowse set-config --profile apollo config.json
Jbrowse configuartion added successfully to apollo
```
> Add CLI command to get and put JBrowse config files in collaboration server

- packages/apollo-collaboration-server/src/changes/changes.service.ts
Fixes https://github.com/GMOD/Apollo3/issues/436
> Set status to 0 for relevant change types

- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/BoxGlyph.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/GeneGlyph.ts
Fixes https://github.com/GMOD/Apollo3/issues/454
> Make clicking on introns in gene glyph select the mRNA

- packages/apollo-collaboration-server/src/jbrowse/jbrowse.service.ts
- packages/apollo-mst/src/AnnotationFeatureModel.ts
- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/Attributes.tsx
- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptBasic.tsx
- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptSequence.tsx
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/BoxGlyph.ts
I've added a new view on the AnnotationFeature model called `transcriptParts`. It returns the list of all parts of a transcript including UTRs, CDS locations, and introns. the `cdsLocations` view on the AnnotationFeature model is now a reference to `transcriptParts` with everything but CDS locations filtered out.
This has been used to replace a lot of cumbersome custom transcript-parsing logic in the TranscriptDetailsWidget to make it easier to maintain and in some cases more accurate. Here are some of the changes:
- "CDS and UTRs" section renamed to "Structure" (as in "Structural annotation")
- Transcript structure is now given in 5\` to 3\` order for both strands
- Extraneous entries in splice sites column removed
- CDSs now color-coded by frame to match track coloring
- New CDS frame …
> Transcript widget upates

- packages/jbrowse-plugin-apollo/src/OntologyManager/index.ts
- packages/jbrowse-plugin-apollo/src/config.ts
- packages/jbrowse-plugin-apollo/src/session/ClientDataStore.ts
- packages/jbrowse-plugin-apollo/src/session/session.ts
With this change, if you want to use a custom ontology as the feature type ontology (instead of the default Sequence Ontology), you can configure it like this in the JBrowse config:
```json
{
"configuration": {
"ApolloPlugin": {
"featureTypeOntologyName": "My Custom Ontology",
"ontologies": [
{
"name": "My Custom Ontology",
"version": "1",
"source": {
"uri": "data/my_custom_ontology.json",
"locationType": "UriLocation"
}
}
]
}
}
}
```
Fixes #458
> Make feature type ontology configurable

- packages/apollo-collaboration-server/src/files/filesUtil.ts
I'm not sure what triggered this bug that is different from before, but when I cleared out my local DB I couldn't load features any more. The error was cryptic, saying something like "length should be >=0, got \<some negative number\>". I finally tracked it down to `read` in `LocalFileGzip` where the "position" and "offset" were swapped. I'm guessing they were both usually 0, which is why it usually worked, but occasionally they were not 0 and it failed.
> Fix occasional error in LocalFileGzip read

- packages/apollo-collaboration-server/src/files/files.service.ts
- packages/apollo-collaboration-server/src/sequence/sequence.service.ts
- packages/apollo-shared/src/Changes/AddAssemblyFromFileChange.ts
As described in #488, I was getting this error when loading data on the demo server:
```
Error: importFeatures failed — 422 Unprocessable Entity 
({"message":"Error: EMFILE: too many open files, open 
'/data/uploads/05dc2a73502099956dce87e417ed886c'","error":"Unprocessable 
Entity","statusCode":422})
```
It turns out #488 did not fix this, so after some more digging I found the solution in this PR. It turns out we have to be a bit careful about making sure we close filehandles when using `LocalFile` so that we don't have a lot of opened files.
> Make sure LocalFile handles get closed

- packages/website/docs/getting-started/try-it-out/02-loading-data.md
Do not cd to `jbrowse_data` otherwise you get:
```
apollo jbrowse get-config
Error: Configuration file "/root/.config/apollo-cli/config.yml" does not
exist. Please run "apollo config" first
```
Write config.json to `data/` so docker can see it otherwise you get:
```
apollo jbrowse set-config config.json
›   Error: File config.json does not exist
```
---
Docs header merged to be more consistent with text.
> Edit how to add evidence tracks jbrowse; Edit header

- packages/apollo-collaboration-server/src/checks/checks.service.ts
- packages/jbrowse-plugin-apollo/cypress/e2e/editFeature.cy.ts
Checks were getting cleared any time a feature check was requested instead of only when the check result was stale.
> Fix checks getting deleted sometimes

- packages/jbrowse-plugin-apollo/src/components/CreateApolloAnnotation.tsx
- packages/jbrowse-plugin-apollo/src/extensions/annotationFromJBrowseFeature.ts
- packages/jbrowse-plugin-apollo/src/extensions/index.ts
- packages/jbrowse-plugin-apollo/src/index.ts
Fixes https://github.com/GMOD/Apollo3/issues/447
> Copy feature from evidence gene track

- packages/apollo-shared/src/GFF3/gff3ToAnnotationFeature.test.ts
- packages/apollo-shared/src/GFF3/gff3ToAnnotationFeature.ts
- packages/jbrowse-plugin-apollo/cypress/e2e/addAssembly.cy.ts
- packages/jbrowse-plugin-apollo/src/extensions/annotationFromJBrowseFeature.test.ts
- packages/jbrowse-plugin-apollo/src/extensions/annotationFromJBrowseFeature.ts
Some imporvements probably needed
> Address issue #504

- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptSequence.tsx
Fixes https://github.com/GMOD/Apollo3/issues/485
> Add protein sequence to transcript detail panel

- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/ApolloFeatureDetailsWidget.tsx
- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/FeatureDetailsNavigation.tsx
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/base.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/layouts.ts
Fixes https://github.com/GMOD/Apollo3/issues/476
> Add navigation to parent/child features in feature details widget

- packages/apollo-mst/src/AnnotationFeatureModel.ts
- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptBasic.tsx
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/BoxGlyph.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/GeneGlyph.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/layouts.ts
- packages/jbrowse-plugin-apollo/src/SixFrameFeatureDisplay/stateModel.ts
- packages/jbrowse-plugin-apollo/src/TabularEditor/HybridGrid/featureContextMenuItems.ts
This uses "transcript" instead of "mRNA" as the base term when doing ontology comparisons since it matches more things we usually want to catch (such as "ncRNA").
> Use "transcript" instead of "mRNA" for base term

- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/LinearApolloDisplay.tsx
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/base.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/layouts.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/mouseEvents.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/rendering.ts
- Change featureLayouts data structure to store feature id instead of the object and access feature from seenFeatures using feature id
- If feature min max range is large, rows boolean array in feature layouts was consuming too much memory leading to crash. Its replaced with a data structure which maintains feature coordinate range for each row
- Clean up seen features outside certain boundary to save memory
- Add loading indicator
Fixes https://github.com/GMOD/Apollo3/issues/522
> Feature layout updates and loading indicator

- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/model.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/LinearApolloDisplay.tsx
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/base.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/layouts.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/mouseEvents.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/rendering.ts
- packages/jbrowse-plugin-apollo/src/OntologyManager/index.ts
A couple fixes here. First fixes the error `DataCloneError: Failed to execute 'put' on 'IDBObjectStore': [object Object] could not be cloned.` when opening the transcript details widget.
The second pre-loads the equivalent types from the ontology for the types we check against in the code. This speeds up gene glyph rendering a lot.
Still potentially some slowness that needs to get tracked down, so starting off as a draft.
Fixes #522
> Improve gene glyph display and performance

- packages/apollo-cli/src/test/test.ts
- packages/apollo-common/src/Check.ts
- packages/apollo-mst/src/CheckResult.ts
- packages/apollo-schemas/src/check.schema.ts
- packages/apollo-schemas/src/checkResult.schema.ts
- packages/apollo-shared/src/Checks/CDSCheck.ts
- packages/jbrowse-plugin-apollo/cypress/e2e/showWarnings.cy.ts
The problem is a mismatch between `name` in CheckResult.ts and `name` in Check.ts. In CheckResult.ts name is (was) something like "InternalStopCodonCheck", but in Check.ts it is something like "CDSCheck". So when calling `clearChecksForFeature` in check.service.ts, the query returns nothing because 'CDSCheck' != 'InternalStopCodonCheck'.
This fix sets `name = "CDSCheck"` in class CDSCheck and adds a property `cause` to CheckResult to store the cause of the failing check, e.g cause = InternalStopCodonCheck. Also add property `causes` to class `Check` to enumerate all the possible causes for the fail.
Note test in test.ts to be fixed: FIXME: Checks stay after invalid operation
> Fix #506: Warnings do not disappear after fixing

- packages/jbrowse-plugin-apollo/src/extensions/annotationFromJBrowseFeature.ts
Fixes an issue found by @shashankbrgowda where if there was a GFF evidence track open and you refreshed the page, you would get this error:
> Fix error when refreshing page with GFF evidence track open

- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/GeneGlyph.ts
It appears to be an off-by-one error. Mouse bp has 1-based coordinates but in intersect2 you need 0-based.
> Fix #548 by setting mouse bp to be 0-based coordinate

- packages/apollo-collaboration-server/src/main.ts
- packages/jbrowse-plugin-apollo/cypress/e2e/editFeature.cy.ts
- packages/jbrowse-plugin-apollo/cypress/e2e/showWarnings.cy.ts
When running
```sh
apollo jbrowse set-config config.json
```
it's possible to get an error that the payload size is too large even with a payload that's under 1 MB. This increases the allowed payload size to 50 MB.
> Increase possible JSON payload size

- packages/jbrowse-plugin-apollo/src/components/AddFeature.tsx
Before this fix the if conditions only set the variable `change` so you always hit the error "No type selected" unless you opt for custom type. Fix by including `return` inside the if blocks.
> Fix if-else to select type of change

- packages/apollo-mst/src/AnnotationFeatureModel.ts
- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptWidgetEditLocation.tsx
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/BoxGlyph.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/GeneGlyph.ts
- packages/jbrowse-plugin-apollo/src/util/annotationFeatureUtils.ts
When the transcript contain single exon thats the whole length of the transcript then we cannot open transcript details widget. This PR adds "Open transcript details" menu option when we right click on transcript or any of its child features.
> Add open transcript details option on right click of child feature

- packages/apollo-shared/src/Validations/ParentChildValidation.ts
- packages/apollo-shared/src/util.ts
This PR edits the post-validation error message to include an identifier accessible to the user. E.g:
```
Error: submitChange failed — 422 Unprocessable Entity ({"message":"Error in backend post-validation: Error: Feature ID=exon10 (_id: 683f1a0331ebb6a40378e739) exceeds the bounds of its parent, ID=mrna05 (_id: 683f1a0331ebb6a40378e73a)","error":"Unprocessable Entity","statusCode":422})
```
If there is no gff_id, use gff_name, with no gff_name fall back on `_id` (`_id` is always reported).
> Print gff_id when reporting errors

- packages/jbrowse-plugin-apollo/src/components/AddFeature.tsx
The dialog box for "Add new feature" requires strand to be + or - for options "Add gene ..." and "Add transcript..." so to avoid unreasonable unstranded genes. 
Option "Add feature with a sequence ontology type" still allows unstranded features.
Also address #617
> New gene or transcript must have strand set

- packages/jbrowse-plugin-apollo/cypress/e2e/downloadGff.cy.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/BoxGlyph.ts
- packages/jbrowse-plugin-apollo/src/components/DownloadGFF3.tsx
In "Export GFF", make the export of fasta sequence optional
> Add option in UI to download GFF without FASTA

- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptSequence.tsx
- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptWidgetEditLocation.tsx
- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptWidgetSummary.tsx
- Update the CDS location when we perform trim operation without validations
- Close translation sequence accordion by default
- Switch cds positions
> Fix:Update CDS locations for translation trim without validation

- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptSequence.tsx
- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptWidgetEditLocation.tsx
- packages/jbrowse-plugin-apollo/src/util/copyToClipboard.ts
If the browsing context is not secure (not HTTPS or localhost), `ClipboardItem` isn't available. This falls back to `document.execCommand('copy')` in that case, which is technically deprecated but still available in all browsers and widely used.
> Fix copy to clipboard not working in some contexts

- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/BoxGlyph.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/GeneGlyph.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/GenericChildGlyph.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloSixFrameDisplay/components/LinearApolloSixFrameDisplay.tsx
- packages/jbrowse-plugin-apollo/src/LinearApolloSixFrameDisplay/glyphs/GeneGlyph.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloSixFrameDisplay/glyphs/Glyph.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloSixFrameDisplay/stateModel/mouseEvents.ts
- packages/jbrowse-plugin-apollo/src/util/annotationFeatureUtils.ts
- packages/jbrowse-plugin-apollo/src/util/glyphUtils.ts
For #643.
I've made some tweaks to general utilities that affect both displays:
* Moved `getContextMenuItemsForFeature` to util as it is common to both
* Transformed `getFeaturesUnderClick` -> `getRelatedFeatures`. This was primarily because one of the arguments, `MousePosition`, is different for each display's state model, yet it was only the `featureAndGlyphUnderMouse.feature` and `bp` that were being used, so I pass them in directly. Otherwise, I believe it now has a more appropriate function name.
I'm aware that a lot of this will need to be updated again for #641; I wanted to make sure these underlying changes were in place before contributing to that PR.
> Context menu list for LASFD

- packages/jbrowse-plugin-apollo/src/components/OpenLocalFile.tsx
Electron v33 removed the method we used of getting the GFF3 file path when running in desktop: https://www.electronjs.org/docs/latest/breaking-changes#removed-filepath
This change uses the now-recommended `webUtils.getPathForFile(file)` instead.
> Fix file path retrieval in desktop

- packages/jbrowse-plugin-apollo/src/LinearApolloSixFrameDisplay/components/LinearApolloSixFrameDisplay.tsx
- packages/jbrowse-plugin-apollo/src/LinearApolloSixFrameDisplay/stateModel/base.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloSixFrameDisplay/stateModel/rendering.ts
I've made a few tweaks to the actual LASFD component, reflecting what was changed in LAD in #642.
A lot of the stripping out that had been performed in #642 happened to already have been accomplished with LASFD due to my earlier decision to remove the embedded sequence display from the annotations track due to a sense it was redundant.
> Bring LASFD into line with recent changes to reference sequence track

- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/LinearApolloDisplay.tsx
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/base.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloSixFrameDisplay/components/LinearApolloSixFrameDisplay.tsx
- packages/jbrowse-plugin-apollo/src/LinearApolloSixFrameDisplay/stateModel/base.ts
I've added a "Check Results" toggle in the Appearance options of both main linear displays (LinearApolloDisplay and LinearApolloSixFrameDisplay).
In testing, unchecking appears to improve performance somewhat, but despite the getting of checkResults values being skipped (see e.g. https://github.com/GMOD/Apollo3/compare/hide-check-results?expand=1#diff-6d7898214bb6134d9daa555085c24057ac55db0b0388d4249eca51b4ebd55f44R176), there is still a process in the session that is iterating over each checkResult value every time the region window changes (see https://github.com/GMOD/Apollo3/blob/main/packages/jbrowse-plugin-apollo/src/session/session.ts#L463). I suppose this can be better solved as part of #594 though.
> Add menu item to hide/show check results

- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/base.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloSixFrameDisplay/stateModel/base.ts
- packages/jbrowse-plugin-apollo/src/components/EditZoomThresholdDialog.tsx
- packages/jbrowse-plugin-apollo/src/util/displayUtils.ts
Fixes #637.
I've currently implemented a dialog box inspired by EditGCContentParamsDialog from jbrowse-components. It's accessed via the Appearance sub-menu in the Annotations track. Two questions: 
1) Is this a bit heavy handed for what is a simple numeric parameter?
2) Do we want to abstract the parameter more? Currently we're presenting the raw bpPerPx unit, which might be confusing? But hopefully the explanatory text in the dialog box demystifies it somewhat.
> Add ability to change zoom display threshold

- packages/jbrowse-plugin-apollo/src/components/OpenLocalFile.tsx
If you opened an assembly from "Open local GFF3" in desktop, it didn't persist since it was getting added as a session assembly. This PR adds it as a standard assembly in desktop instead, so it persist after closing an opening JBrowse Desktop.
> Fix assembly not persisting in desktop when opened vi UI

- packages/jbrowse-plugin-apollo/cypress/e2e/lockSession.cy.ts
- packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/addMenuItems.ts
- packages/jbrowse-plugin-apollo/src/ChangeManager.ts
- packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/LinearApolloDisplay.tsx
- packages/jbrowse-plugin-apollo/src/session/session.ts
- packages/jbrowse-plugin-apollo/src/util/displayUtils.ts
This PR introduces the "locked session" option (issue #659). This is how it looks at the moment (note lock icon on the right):
There is a test in `cypress/e2e/lockSession.cy.ts`.
> Introduce locked annotation mode (#659)

- packages/apollo-shared/src/Changes/AddRefSeqAliasesChange.ts
- packages/jbrowse-plugin-apollo/src/BackendDrivers/CollaborationServerDriver.ts
- packages/jbrowse-plugin-apollo/src/components/AddRefSeqAliases.tsx
Details
- Refname alias configuration UI data grid row selection stopped working (may be because of data grid upgrade), changed to use GridRowSelectionModel to get the row ids. 
- Improvements in initializing refname alias state
> Fix Refname alias data grid issues 

- packages/apollo-shared/src/Checks/CDSCheck.ts
- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/BasicInformation.tsx
- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/NumberTextField.tsx
- packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptWidgetEditLocation.tsx
Make CDS editing in input boxes similar to translation panel. Checks If there is a underlying exon and if start/end of CDS don't overlap. 
Requested by Havana
> Simplify CDS editing in transcript details widget

- packages/jbrowse-plugin-apollo/src/components/ManageChecks.tsx
In the `ManageChecks` component, a query that should have been to a relative URL was instead to an absolute one.
Fixes #701
> Fix ManageChecks when collaboration server is in subdirectory
