GMOD/Apollo3

packages/jbrowse-plugin-apollo/jbrowse_config.json, packages/jbrowse-plugin-apollo/src/ApolloAuthWidget/components/ApolloAuthWidget.tsx, packages/jbrowse-plugin-apollo/src/ApolloAuthWidget/index.ts, packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/components/ApolloLoginForm.tsx, packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/configSchema.ts, packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/index.ts, packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/model.ts, packages/jbrowse-plugin-apollo/src/index.ts
Please, find LoginWidget branch for reviewing. In model.ts there is one
// eslint-disable-next-line @typescript-eslint/no-explicit-any 
that I was not able to get rid of.
=> Initial commit for LoginWidget

packages/apollo-collaboration-server/src/assemblies/schemas/assembly.schema.ts, packages/apollo-collaboration-server/src/features/schemas/feature.schema.ts, packages/apollo-collaboration-server/src/refSeqs/schemas/refSeq.schema.ts
Adds initial schemas to base further work off of.
Resolves #50
=> Add Mongodb schemas for features, refSeqs, and assemblies

packages/apollo-collaboration-server/src/entity/gff3Object.dto.ts, packages/apollo-collaboration-server/src/features/features.controller.ts, packages/apollo-collaboration-server/src/features/features.service.ts, packages/apollo-schemas/src/feature.schema.ts
This branch covers features that are listed in https://github.com/GMOD/jbrowse-plugin-apollo/issues/62
Closes #62
=> Add feature range fetching endpoint

packages/apollo-collaboration-server/src/app.module.ts, packages/apollo-collaboration-server/src/refSeqChunks/dto/create-refSeqChunk.dto.ts, packages/apollo-collaboration-server/src/refSeqChunks/dto/get-sequence.dto.ts, packages/apollo-collaboration-server/src/refSeqChunks/dto/update-refSeqChunk.dto.ts, packages/apollo-collaboration-server/src/refSeqChunks/entities/refSeqChunk.entity.ts, packages/apollo-collaboration-server/src/refSeqChunks/refSeqChunks.controller.spec.ts, packages/apollo-collaboration-server/src/refSeqChunks/refSeqChunks.controller.ts, packages/apollo-collaboration-server/src/refSeqChunks/refSeqChunks.module.ts, packages/apollo-collaboration-server/src/refSeqChunks/refSeqChunks.service.spec.ts, packages/apollo-collaboration-server/src/refSeqChunks/refSeqChunks.service.ts, packages/apollo-collaboration-server/src/refSeqs/refSeqs.controller.ts, packages/apollo-collaboration-server/src/refSeqs/refSeqs.module.ts, packages/apollo-schemas/src/index.ts, packages/apollo-schemas/src/refSeq.schema.ts, packages/apollo-schemas/src/refSeqChunk.schema.ts
Closes #66
Does not include loading sequence from FASTA or GFF3 yet, but we'll be able to load sequences when a PR implementing #67 is merged.
=> Add refSeqChunks schema and module

packages/apollo-collaboration-server/.development.env, packages/apollo-collaboration-server/src/change/change.controller.ts, packages/apollo-collaboration-server/src/change/change.module.ts, packages/apollo-collaboration-server/src/change/change.service.ts, packages/apollo-collaboration-server/src/change/dto/create-change.dto.ts, packages/apollo-schemas/src/changeLog.schema.ts, packages/apollo-schemas/src/index.ts, packages/apollo-shared/src/ChangeManager/Change.ts, packages/apollo-shared/src/ChangeManager/LocationEndChange.ts, packages/apollo-shared/src/ChangeManager/LocationStartChange.ts
=> Add schema for Changes

packages/apollo-shared/src/ChangeManager/ChangeManager.ts, packages/jbrowse-plugin-apollo/src/ApolloView/stateModel.ts
Ready for testing. However, this branch still uses to load initial GFF3 data into cache at startup but submitChange() -method makes changes to Mongo. Therefore, testing is a challenging.
=> Add simple "Undo" to Apollo UI

.github/workflows/pull_request.yml, .github/workflows/push.yml, packages/jbrowse-plugin-apollo/package.json, packages/jbrowse-plugin-apollo/src/ApolloDetailsView/components/ApolloDetailsView.tsx, yarn.lock
This was needed after recent changes to JBrowse.
=> Fix editing type in ApolloDetailsView

packages/apollo-collaboration-server/src/files/files.controller.ts, packages/apollo-collaboration-server/src/files/files.service.ts, packages/apollo-shared/src/ChangeManager/AddAssemblyAndFeaturesFromFileChange.ts, packages/apollo-shared/src/ChangeManager/AddAssemblyFromFileChange.ts, packages/apollo-shared/src/ChangeManager/AddFeaturesFromFileChange.ts, packages/jbrowse-plugin-apollo/src/components/AddAssembly.tsx, packages/jbrowse-plugin-apollo/src/components/ImportFeatures.tsx
=> Delete stored files on failed import

packages/apollo-collaboration-server/src/features/features.controller.ts, packages/jbrowse-plugin-apollo/package.json, packages/jbrowse-plugin-apollo/src/ApolloView/components/CollaborationSetup.tsx, packages/jbrowse-plugin-apollo/src/ApolloView/stateModel.ts, yarn.lock
Along with https://github.com/GMOD/jbrowse-components/pull/3084, this will show a descriptive error instead of freezing when "Get sequence" is selected from the rubber band menu. Actual sequence retrieval will be possible when #44 is resolved.
=> Fix "Get sequence"

packages/jbrowse-plugin-apollo/src/ApolloDetailsView/components/ApolloDetailsView.tsx, packages/jbrowse-plugin-apollo/src/ApolloDetailsView/stateModel.ts, packages/jbrowse-plugin-apollo/src/ApolloRenderer/components/ApolloRendering.tsx, packages/jbrowse-plugin-apollo/src/ApolloView/stateModel.ts, packages/jbrowse-plugin-apollo/src/components/AddAssembly.tsx, packages/jbrowse-plugin-apollo/src/components/CopyFeature.tsx, packages/jbrowse-plugin-apollo/src/components/CopyFeaturesAndAnnotations.tsx
Ready for testing. 
Note that before full test (i.e. calling backend) the issue [Copy feature and associated annotations from assembly to another #118](https://github.com/GMOD/Apollo3/issues/118) -must merged.
=> Add context menu item to copy feature

packages/apollo-collaboration-server/src/authentication/authentication.service.ts, packages/apollo-collaboration-server/src/utils/commonUtilities.ts, packages/apollo-collaboration-server/src/utils/payloadObject.ts, packages/apollo-collaboration-server/src/utils/strategies/jwt.strategy.ts, packages/apollo-collaboration-server/src/utils/validation/AuthorizationValidation.ts, packages/apollo-shared/src/Common/index.ts, packages/apollo-shared/src/Common/jwtPayload.ts, packages/apollo-shared/src/Common/payloadObject.ts, packages/apollo-shared/src/index.ts, packages/jbrowse-plugin-apollo/package.json, packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/model.ts, packages/jbrowse-plugin-apollo/src/ApolloRenderer/components/ApolloRendering.tsx, yarn.lock
=> Add role info to JWT payload

packages/apollo-collaboration-server/src/changes/changes.module.ts, packages/apollo-collaboration-server/src/changes/changes.service.ts, packages/apollo-collaboration-server/src/changes/dto/create-change.dto.ts, packages/apollo-collaboration-server/src/counters/counters.module.ts, packages/apollo-collaboration-server/src/counters/counters.service.ts, packages/apollo-schemas/src/change.schema.ts, packages/apollo-schemas/src/counter.schema.ts, packages/apollo-schemas/src/index.ts, packages/apollo-shared/src/ChangeManager/changes/abstract/Change.ts, packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/model.ts, packages/jbrowse-plugin-apollo/src/components/ViewChangeLog.tsx
All the infrastructure seems to be there and passing linting
=> Add increment to changes collection

packages/apollo-collaboration-server/src/authentication/authentication.service.ts
=> Fix bug where admin options didn't appear on first login

packages/apollo-collaboration-server/src/features/features.module.ts, packages/apollo-collaboration-server/src/features/features.service.ts, packages/apollo-collaboration-server/src/ontologies/ontologies.service.ts, packages/apollo-collaboration-server/src/operations/operations.module.ts, packages/apollo-shared/src/Operations/GetFeaturesOperation.ts, packages/apollo-shared/src/Operations/index.ts
=> Add GetFeaturesOperation

packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/ApolloDetails.tsx, packages/jbrowse-plugin-apollo/src/components/ModifyFeatureAttribute.tsx
=> Add attributes column to details view

.eslintrc.js, packages/apollo-collaboration-server/src/changes/changes.service.ts, packages/apollo-collaboration-server/src/global-exceptions.filter.ts, packages/apollo-collaboration-server/src/main.ts, packages/apollo-collaboration-server/src/operations/operations.service.ts, packages/apollo-collaboration-server/src/users/users.service.ts, packages/apollo-shared/src/Changes/AddFeatureChange.ts, packages/jbrowse-plugin-apollo/src/ApolloInternetAccount/model.ts, packages/jbrowse-plugin-apollo/src/ApolloSixFrameRenderer/components/ApolloRendering.tsx, packages/jbrowse-plugin-apollo/src/BackendDrivers/CollaborationServerDriver.ts, packages/jbrowse-plugin-apollo/src/ChangeManager.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/ApolloDetails.tsx, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/Glyph.ts, packages/jbrowse-plugin-apollo/src/components/AddAssembly.tsx, packages/jbrowse-plugin-apollo/src/components/AddFeature.tsx, packages/jbrowse-plugin-apollo/src/components/CopyFeature.tsx, packages/jbrowse-plugin-apollo/src/components/DeleteAssembly.tsx, packages/jbrowse-plugin-apollo/src/components/DeleteFeature.tsx, packages/jbrowse-plugin-apollo/src/components/GoAutocomplete.tsx, packages/jbrowse-plugin-apollo/src/components/ImportFeatures.tsx, packages/jbrowse-plugin-apollo/src/components/ManageUsers.tsx, packages/jbrowse-plugin-apollo/src/components/ModifyFeatureAttribute.tsx, packages/jbrowse-plugin-apollo/src/components/ViewChangeLog.tsx, packages/jbrowse-plugin-apollo/src/components/index.ts
I tested this fix several times and I was not anymore able to re-produce any error even I fired automatically X times AddFeatureChange -change from AddFeature.tsx
=> Fix for occasional server when adding or removing a feature

.vscode/tasks.json, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/ApolloDetails.tsx, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/index.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/layouts.ts, packages/jbrowse-plugin-apollo/src/TabularEditor/DataGrid.tsx, packages/jbrowse-plugin-apollo/src/TabularEditor/TabularEditorPane.tsx, packages/jbrowse-plugin-apollo/src/TabularEditor/index.ts, packages/jbrowse-plugin-apollo/src/makeDisplayComponent.tsx, packages/jbrowse-plugin-apollo/src/session.ts
Improves the details view display by:
* removing the "click a feature" message, which improved the scroll bar tidiness
* scrolling the features canvas when the details view pops up so that the selected feature stays visible
* refactoring in preparation for new tabular editing functionality
ref #220
=> improved details view

packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/CanonicalGeneGlyph.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/Glyph.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/ImplicitExonGeneGlyph.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/mouseEvents.ts
Fixes https://github.com/GMOD/Apollo3/issues/247
=> Make subfeatures selectable in gene glyphs

.devcontainer/devcontainer.json, packages/apollo-collaboration-server/.development.env, packages/jbrowse-plugin-apollo/src/components/AddFeature.tsx
=> Warn when adding child of there are no valid ontology terms

packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/LinearApolloDisplay.tsx, packages/jbrowse-plugin-apollo/src/TabularEditor/HybridGrid/Feature.tsx, packages/jbrowse-plugin-apollo/src/TabularEditor/HybridGrid/HybridGrid.tsx, packages/jbrowse-plugin-apollo/src/makeDisplayComponent.tsx
Covers this issue: https://github.com/GMOD/Apollo3/issues/255
=> Make table visible by default, other table improvements

packages/jbrowse-plugin-apollo/src/components/DownloadGFF3.tsx
Fixes DownloadGFF3 issue (download was not started)
=> Fix bug that keeps GFF3 from downloading

packages/apollo-collaboration-server/src/main.ts, packages/apollo-collaboration-server/src/utils/FileStorageEngine.ts
Added zlib.constants.Z_BEST_SPEED -option to createGzip() method
=> Fix problem uploading large files

packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/layouts.ts
Fixes https://github.com/GMOD/Apollo3/issues/270
=> Fix crash with very long features

packages/apollo-collaboration-server/src/features/features.service.ts, packages/jbrowse-plugin-apollo/README.md, packages/jbrowse-plugin-apollo/cypress/e2e/addAssembly.cy.ts, packages/jbrowse-plugin-apollo/cypress/e2e/editFeature.cy.ts, packages/jbrowse-plugin-apollo/cypress/e2e/searchFeatures.cy.ts, packages/jbrowse-plugin-apollo/cypress/support/commands.ts, packages/jbrowse-plugin-apollo/cypress/support/index.d.ts, packages/jbrowse-plugin-apollo/test_data/onegene.fasta.gff3, packages/jbrowse-plugin-apollo/test_data/space.gff3, packages/jbrowse-plugin-apollo/test_data/volvox.fasta.gff3
Fixes #262 by quoting search string in mongoose query.
=> Fix attribute search with spaces, add more tests

packages/apollo-collaboration-server/src/checks/checks.controller.ts, packages/apollo-collaboration-server/src/checks/checks.module.ts, packages/apollo-collaboration-server/src/checks/checks.service.ts, packages/apollo-collaboration-server/src/features/features.module.ts, packages/apollo-collaboration-server/src/features/features.service.ts, packages/apollo-collaboration-server/src/refSeqs/refSeqs.module.ts, packages/apollo-shared/src/Checks/CDSCheck.ts, packages/jbrowse-plugin-apollo/src/components/ViewCheckResults.tsx, packages/jbrowse-plugin-apollo/src/index.ts
Resolves #316 
@dariober, I've moved your commits into this branch so I could merge the previous commits to the other branch.
=> Add check result UI

packages/apollo-collaboration-server/src/checks/checks.service.ts, packages/apollo-collaboration-server/src/features/features.module.ts, packages/apollo-mst/src/AnnotationFeature.ts, packages/apollo-schemas/src/checkResult.schema.ts, packages/apollo-shared/src/Checks/CDSCheck.ts, packages/jbrowse-plugin-apollo/cypress/e2e/editFeature.cy.ts, packages/jbrowse-plugin-apollo/cypress/support/commands.ts, packages/jbrowse-plugin-apollo/src/BackendDrivers/BackendDriver.ts, packages/jbrowse-plugin-apollo/src/BackendDrivers/CollaborationServerDriver.ts, packages/jbrowse-plugin-apollo/src/BackendDrivers/InMemoryFileDriver.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/LinearApolloDisplay.tsx, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/BoxGlyph.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/CanonicalGeneGlyph.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/GenericChildGlyph.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/Glyph.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/ImplicitExonGeneGlyph.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/layouts.ts, packages/jbrowse-plugin-apollo/src/makeDisplayComponent.tsx, packages/jbrowse-plugin-apollo/src/session/ClientDataStore.ts, packages/jbrowse-plugin-apollo/test_data/cdsChecks/stopcodon.gff3, packages/jbrowse-plugin-apollo/test_data/onegene.fasta.gff3
=> Render checks in track

packages/jbrowse-plugin-apollo/src/BackendDrivers/DesktopFileDriver.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/Glyph.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/base.ts, packages/jbrowse-plugin-apollo/src/TabularEditor/HybridGrid/featureContextMenuItems.ts, packages/jbrowse-plugin-apollo/src/components/CopyFeature.tsx, packages/jbrowse-plugin-apollo/src/components/DeleteFeature.tsx, packages/jbrowse-plugin-apollo/src/components/ModifyFeatureAttribute.tsx, packages/jbrowse-plugin-apollo/src/util/index.ts
=> Fix crash on feature context menu on desktop

packages/jbrowse-plugin-apollo/src/index.ts, packages/jbrowse-plugin-apollo/src/util/loadAssemblyIntoClient.ts
=> Add checks for locally opened files

packages/apollo-shared/src/Changes/DeleteAssemblyChange.ts
Fix for https://github.com/GMOD/Apollo3/issues/334
=> Bug: Assembly not deleted from JBrowse when it's deleted from Apollo

packages/jbrowse-plugin-apollo/src/extensions/annotationFromPileup.ts, packages/jbrowse-plugin-apollo/src/extensions/index.ts, packages/jbrowse-plugin-apollo/src/index.ts
=> Create annotation from alignment read

packages/apollo-collaboration-server/src/export/export.service.ts, packages/apollo-shared/src/Changes/StrandChange.ts, packages/apollo-shared/src/Changes/index.ts, packages/apollo-shared/src/util.ts, packages/jbrowse-plugin-apollo/src/BackendDrivers/DesktopFileDriver.ts, packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/ApolloFeatureDetails.tsx, packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/ApolloFeatureDetailsWidget.tsx, packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/Attributes.tsx, packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/BasicInformation.tsx, packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/NumberTextField.tsx, packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/Sequence.tsx, packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/StringTextField.tsx, packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/index.ts, packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/model.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/Glyph.ts, packages/jbrowse-plugin-apollo/src/OntologyManager/util.ts, packages/jbrowse-plugin-apollo/src/components/AddChildFeature.tsx, packages/jbrowse-plugin-apollo/src/index.ts
There is a issue when user refreshes browser while widget is open
=> Issue339 edit single feature widget

packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/CanonicalGeneGlyph.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/ImplicitExonGeneGlyph.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/mouseEvents.ts, packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/rendering.ts
Fixes https://github.com/GMOD/Apollo3/issues/349
=> Color CDS by reading frame

packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/ApolloFeatureDetailsWidget.tsx, packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/RelatedFeature.tsx
=> Add ability to go to related features from feature editor widget

packages/jbrowse-plugin-apollo/src/session/session.ts
=> Fix ability to save and remove multiple evidence tracks to collaboration server

packages/apollo-collaboration-server/src/features/features.controller.ts, packages/apollo-collaboration-server/src/features/features.service.ts
Fixes https://github.com/GMOD/Apollo3/issues/357#issuecomment-2375316048
=> Add ability to get parent feature from features endpoint

packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/base.ts
Fixes https://github.com/GMOD/Apollo3/issues/463
=> Don't fetch sequence when zoomed out in Apollo Track

packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/GeneGlyph.ts
Fixes https://github.com/GMOD/Apollo3/issues/462
=> Draw background on genes

packages/jbrowse-plugin-apollo/src/components/FilterFeatures.tsx
Fix filter feature type input box width
=> Fix filter feature type input box width

packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptWidgetEditLocation.tsx
- Fixes transcript widget location editing
- Fix trim functionality for reverse strand translation sequence
=> Improve transcript widget edit location action

packages/apollo-shared/src/GFF3/annotationFeatureToGFF3.ts, packages/jbrowse-plugin-apollo/src/extensions/annotationFromPileup.ts
- Open "Create Apollo Annotation" dialog similar to copying from gff track. Provide ability to choose destination gene or copy transcript as part of new gene.
- Fixes incorrect exon location issue 
- Remove CDS creation
Fixes
#590
#593
=> Fix and improve adding feature from BAM track to Apollo track

packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget/TranscriptSequence.tsx
=> Add sequence length to and reformat the sequence panel FASTA header

packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/GeneGlyph.ts, packages/jbrowse-plugin-apollo/src/config.ts, packages/jbrowse-plugin-apollo/src/index.ts, packages/jbrowse-plugin-apollo/src/session/session.ts
pseudogenes and pseudogenic_transcripts have light blue background
Transcripts without CDS have light red background
Everything else has default background. For example:
=> Background color for non coding transcripts #660
